sources:
  - name: source_bronze
    database: workspace  
    schema: bronze  
    tables:
      - name: trips
  

  - name: source_silver
    database: workspace  
    schema: silver  
    tables:
      - name: customers
      - name: locations
      - name: drivers
      - name: payments
      - name: vehicles

